### ISSUE TITLE
which machine act as gateway for node VLAN interface

### ISSUE THREAD

**Issue by nirmoy** [DevNetSandbox/sbx_acik8s#4]
[developer@sbx29kube01 tmp]$ ip r s
default via 172.20.29.1 dev ens224.960 proto static metric 400 
10.0.0.0/16 dev ens224.4093 proto kernel scope link src 10.0.216.89 
169.254.0.0/16 dev ens224.4093 scope link metric 1006 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
172.20.0.0/24 dev ens192 proto kernel scope link src 172.20.0.217 metric 100 
172.20.29.0/26 dev ens224.960 proto kernel scope link src 172.20.29.11 metric 400 
224.0.0.0/4 dev ens224.4093 scope link 

Which machine has 172.20.29.1, is this from ACI ?

**Comment by hpreston** [comment]
@nirmoy I'm sorry for the delay in responding.. just noticed the open issue.  

The gateway for the Node VLAN is provided by the ACI fabric.  If you look within the tenant for a pod at the Bridge Domains, you'll find `kube-node-bd`.  This has the subnet for the Node VLAN.
